name: Check PR Description

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-description:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Description
        uses: actions/github-script@v6
        with:
          script: |
            const description = context.payload.pull_request.body;
            const defaultTemplate = `
### Description
<!-- Briefly explain what this PR does and why it is needed -->

- **What has changed?**  
  <!-- List the key changes or features added/modified -->

- **Why is this change necessary?**  
  <!-- State the problem it solves or the improvement it introduces -->

- **Relevant links or references:**  
  <!-- e.g., related tickets, issues, or documentation links -->

### Checklist
- [ ] I have tested my changes.
- [ ] I have updated the documentation if necessary.
- [ ] This PR follows the coding guidelines of the project.
`;

            if (!description || description.trim().length <= defaultTemplate.trim().length) {
              throw new Error(
                "A descrição do PR é obrigatória e deve ser preenchida além do template padrão."
              );
            }
